language: generic 
sudo: required
service:
  - docker
before_install:
  - docker build -t iwinokurow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iwinokurow/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-eu-central-1-571169730856"
  bucket_path: "docker-react1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

